const dataDB = [
    {
        idProduct: 1,
        category: "cafe",
        title: "Macchiato",
        subtitle: "Con espuma",
        description: "En este café, la leche al vapor está manchando el shot de espresso. Para hacer un macchiato, añade a un shot de espresso solo un chorrito de leche al vapor. Intenta buscar una proporción de aproximadamente 90% de café a 10% de leche.",
        ingredients: "Espresso shot, espuma",
        price: "450",
        pictureUrl: "https://i.ibb.co/k5ffcTt/machiato.png",
        roasted: "Medium",
        milk: true,
        raiting: 4.5,
        stock: 5
    },
    {
        idProduct: 2,
        category: "cafe",
        title: "Flat White",
        subtitle: "Con 2oz de espresso",
        description: "Bebida de café inventada en Australia en la década de 1980. Se prepara agregando una capa fina de leche caliente o microespuma (leche vaporizada con pequeñas burbujas y una consistencia cremosa) en un café expreso, simple o doble.",
        ingredients: "2OZ Espresso, leche",
        price: "400",
        pictureUrl: "https://i.ibb.co/pn0jHNW/flat-white.png",
        roasted: "High",
        milk: true,
        raiting: 4.9,
        stock: 4
    },
    {
        idProduct: 3,
        category: "cafe",
        title: "Latte",
        subtitle: "Con leche",
        description: "El café latte se prepara con una o dos dosis de expreso (1/3 de la bebida) y 2/3 de leche calentada con vapor, con una pequeña capa (1 cm) de espuma de leche.",
        ingredients: "Espresso, leche",
        price: "380",
        pictureUrl: "https://i.ibb.co/pxSZGCT/latte.png",
        roasted: "Low",
        milk: true,
        raiting: 4.1,
        stock: 2
    },
    {
        idProduct: 4,
        category: "cafe",
        title: "Doppio",
        subtitle: "Con 2oz de espresso",
        description: "El doppio es un café espresso hecho con dos cargas, extraído utilizando un filtro de café doble. Esto resulta en 60 ml de bebida, el doble de un espresso convencional.",
        ingredients: "2oz Espresso",
        price: "450",
        pictureUrl: "https://i.ibb.co/1QqFfDD/dopio.png",
        roasted: "High",
        milk: false,
        raiting: 4.5,
        stock: 7
    },
    {
        idProduct: 5,
        category: "cafe",
        title: "Cappuccino",
        subtitle: "Con espuma",
        description: "Bebida clásica con espresso y leche. Un malentendido común es pensar que sigue la regla de los tercios: un tercio de espresso, un tercio de leche cremada y un tercio de espuma de leche.",
        ingredients: "Espresso, leche, espuma",
        price: "390",
        pictureUrl: "https://i.ibb.co/h9cXBxF/coffe-1.png",
        roasted: "High",
        milk: true,
        raiting: 4.3,
        stock: 1
    },
    {
        idProduct: 6,
        category: "cafe",
        title: "Americano",
        subtitle: "Con agua caliente",
        description: "Preparación de procedencia estadounidense, en la que se diluye el café espresso en agua caliente, reduciendo así la intensidad de su sabor.",
        ingredients: "Espresso, agua caliente",
        price: "420",
        pictureUrl: "https://i.ibb.co/ZhQTSxn/coffe-1.png",
        roasted: "High",
        milk: false,
        raiting: 4.2,
        stock: 0
    },
    {
        idProduct: 7,
        category: "cafe",
        title: "Espresso",
        subtitle: "Con 1oz de espresso",
        description: "Café negro fuerte que se forma cuando el agua caliente pasa a mucha presión través de los granos de café molidos. Si bien esto puede sonar similar a un café estándar, son muy diferentes. El espresso requiere mucha más presión y mucho menos tiempo de preparación que el café.",
        ingredients: "1oz Espresso",
        price: "400",
        pictureUrl: "https://i.ibb.co/4fTxcKv/coffe-1.png",
        roasted: "High",
        milk: false,
        raiting: 4.4,
        stock: 4
    },
    {
        idProduct: 8,
        category: "cafe",
        title: "Lungo",
        subtitle: "Con espresso",
        description: "La diferencia entre café lungo y espresso normal es esencialmente el tiempo de extracción, mayor en el caso del lungo y la cantidad de agua utilizada en esa extracción, aproximadamente el doble de la utilizada en un espresso normal.",
        ingredients: "Espresso",
        price: "380",
        pictureUrl: "https://i.ibb.co/bsmp31b/coffe-1.png",
        roasted: "High",
        milk: false,
        raiting: 3.8,
        stock: 6
    },
    {
        idProduct: 9,
        category: "cafe",
        title: "Mocha",
        subtitle: "Con leche a vapor",
        description: "Suele llevar un tercio de expreso y dos tercios de leche vaporizada, pero se añade una parte de chocolate, normalmente en forma de jarabe de chocolate, aunque algunas máquinas usan chocolate en polvo instantáneo.",
        ingredients: "Espresso, chocolate, leche a vapor",
        price: "430",
        pictureUrl: "https://i.ibb.co/9ZQBwRY/coffe-1.png",
        roasted: "High",
        milk: true,
        raiting: 4.2,
        stock: 1
    },
    {
        idProduct: 10,
        category: "cafe",
        title: "Irish",
        subtitle: "Con whisky",
        description: "El Café irlandés o Irish coffee es un cóctel que consiste en la mezcla de whisky irlandés, una cucharada de azúcar, café y finalmente va cubierto por dos centímetros de crema de leche o nata semimontada.",
        ingredients: "Cafe, whisky, azucar, crema",
        price: "500",
        pictureUrl: "https://i.ibb.co/dmNdjwJ/coffe-2.png",
        roasted: "High",
        milk: true,
        raiting: 4.7,
        stock: 3
    },
    {
        idProduct: 11,
        category: "granos",
        title: "Perú",
        subtitle: "250g",
        description: "Presentando notas especiadas, un dulzor bien presente que aporta cuerpo y un final cítrico que perdura en boca. Lo recomendamos preferentemente para metodos que potencien más aún este cuerpo como el espresso o la moka italiana.",
        ingredients: "Vainilla, Miel, Almendras, Mandarina",
        price: "3200",
        pictureUrl: "https://i.ibb.co/t2cZkh3/coffe-3.png",
        roasted: "Light",
        milk: false,
        raiting: 4.3,
        stock: 4
    },
    {
        idProduct: 12,
        category: "granos",
        title: "Colombia",
        subtitle: "250g",
        description: "Un café dulce, con buen cuerpo y muy fácil de tomar, para todo tipo de paladares. Desde los que recien se esten iniciando en el mundo del café de especialidad hasta los baristas más expertos van a disfrutar de este café.",
        ingredients: "Chocolate con leche, caramelo y naranja",
        price: "2700",
        pictureUrl: "https://i.ibb.co/rb0Qpq3/coffe-3.png",
        roasted: "Medium",
        milk: false,
        raiting: 4.7,
        stock: 2
    },
    {
        idProduct: 13,
        category: "granos",
        title: "Guatemala",
        subtitle: "250g",
        description: "Un café muy dulce y balanceado. Como morder una manzana roja en su punto justo. Presenta un buen cuerpo pronunciado y cremos.",
        ingredients: "Chocolate con leche, avellana, almendra, manzana roja y uva blanca",
        price: "3200",
        pictureUrl: "https://i.ibb.co/gVbLRjj/coffe-4.png",
        roasted: "Light",
        milk: false,
        raiting: 4.5,
        stock: 4
    },
    {
        idProduct: 14,
        category: "granos",
        title: "Papúa Nueva Guinea",
        subtitle: "250g",
        description: "Un café exótico para paladares exquisitos, simplemente delicioso. Desde Oceanía viene cruzando el pacífico estos granos increíbles nacido en Wahgi Valley, al oeste de la isla de Papúa Nueva Guinea",
        ingredients: "Manzana cocida, canela, caramelo y pomelo rosado.",
        price: "3900",
        pictureUrl: "https://i.ibb.co/5nFm388/coffe-5.png",
        roasted: "Light",
        milk: false,
        raiting: 4.2,
        stock: 6
    },
    {
        idProduct: 15,
        category: "granos",
        title: "Colombia",
        subtitle: "1kg",
        description: "Un café dulce, con buen cuerpo y muy fácil de tomar, para todo tipo de paladares. Desde los que recien se esten iniciando en el mundo del café de especialidad hasta los baristas más expertos van a disfrutar de este café.",
        ingredients: "Chocolate con leche, caramelo y naranja",
        price: "9200",
        pictureUrl: "https://i.ibb.co/HTLz3P5/coffe-6.png",
        roasted: "Medium",
        milk: false,
        raiting: 4.7,
        stock: 3
    },
    {
        idProduct: 16,
        category: "capsulas",
        title: "Cappuccino",
        subtitle: "12 unidades",
        description: "Cappuccino que combina un café espresso de tueste oscuro y una crema densa y sedosa. Diseñado para las cafeteras NESCAFÉ® Dolce Gusto®.",
        ingredients: "Cafe",
        price: "1015",
        pictureUrl: "https://i.ibb.co/xjmsg9X/coffe-7.png",
        roasted: "Dark",
        milk: false,
        raiting: 4.1,
        stock: 1
    },
    {
        idProduct: 17,
        category: "capsulas",
        title: "Americano",
        subtitle: "12 unidades",
        description: "House Blend Americano con intensas notas de caramelo y una combinación perfecta de aroma, cuerpo y sabor.",
        ingredients: "Cafe",
        price: "1015",
        pictureUrl: "https://i.ibb.co/X4bYy3d/coffe-8.png",
        roasted: "Dark",
        milk: false,
        raiting: 4.9,
        stock: 8
    },
    {
        idProduct: 18,
        category: "capsulas",
        title: "Macchiato",
        subtitle: "6 unidades",
        description: "Descubrí el clásico y cremoso Caramel Macchiato diseñado para las cafeteras NESCAFÉ® Dolce Gusto®.",
        ingredients: "Cafe",
        price: "1015",
        pictureUrl: "https://i.ibb.co/5YMhBHV/coffe-10.png",
        roasted: "Dark",
        milk: false,
        raiting: 4.6,
        stock: 4
    }
];
export default dataDB;